### YamlMime:Landing
title: Dokumentation zu Docker in Azure
summary: 'Docker ist eine beliebte Plattform für die Containerverwaltung und Imageerstellung, die es Ihnen ermöglicht, schnell mit Containern unter Linux und Windows zu arbeiten. Erfahren Sie, wie Sie Docker in Azure nutzen:'
metadata:
  title: Dokumentation zu Docker in Azure
  description: Docker ist eine beliebte Plattform für die Containerverwaltung und Imageerstellung, die es Ihnen ermöglicht, schnell mit Containern unter Linux und Windows zu arbeiten.
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: 700c5b1e113de32b80b3d716db915836049128ec
  ms.sourcegitcommit: 4feb198becb7a6ff9e6b42be9185e07539022f17
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/04/2020
  ms.locfileid: "89470118"
landingContent:
- title: Bereitstellen von Docker in Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Bereitstellen der Schnellstartvorlage „Docker on Ubuntu Server“
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Erste Schritte
  linkLists:
  - linkListType: tutorial
    links:
    - text: Ausführen einer Python-Web-App (Django) mit PostgreSQL in Azure App Service
      url: ../app-service/tutorial-python-postgresql-app.md
    - text: Erstellen einer Entwicklungsinfrastruktur auf einem virtuellen Linux-Computer in Azure mit Jenkins, GitHub und Docker
      url: /azure/developer/jenkins/pipeline-with-github-and-docker
- title: Ressourcen
  linkLists:
  - linkListType: reference
    links:
    - text: Docker for Azure (Docker für Azure)
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Docker-Azure-Treiber
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Informationen zu Docker
      url: https://docker.com
