- name: Docker-Dokumentation
  href: index.md
- name: Schnellstart
  expanded: true
  items:
    - name: Bereitstellen eines virtuellen Ubuntu-Computers mit Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: Tutorials
  items:
    - name: Python-Web-App mit Docker und PostgreSQL
      href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'CI/CD mit Docker, Jenkins und Linux'
      href: /azure/jenkins/tutorial-jenkins-github-docker-cicd
- name: Anleitungen
  items:
    - name: Docker-VM-Erweiterung
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker-Computer
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker-Containerregistrierung
      href: /azure/container-registry/container-registry-get-started-portal
- name: Ressourcen
  items:
    - name: Azure-Roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker-Azure-Treiber
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker-Azure-Website
      href: 'https://www.docker.com/docker-azure'
    - name: Docker-Website
      href: 'https://docker.com'