- name: Kubernetes mit Azure Arc-Aktivierung
  href: index.yml
- name: Übersicht
  items:
    - name: Informationen zu Kubernetes mit Azure Arc-Aktivierung
      href: overview.md
    - name: Azure Arc-Validierungsprogramm
      href: validation-program.md
- name: Schnellstarts
  items:
    - name: Verbinden eines Clusters mit Azure Arc
      href: quickstart-connect-cluster.md
- name: Tutorials
  items:
    - name: Bereitstellen von Konfigurationen mithilfe von GitOps
      href: tutorial-use-gitops-connected-cluster.md
    - name: Implementieren von CI/CD mit GitOps
      href: tutorial-gitops-ci-cd.md
- name: Konzepte
  items:
    - name: Agent-Architektur
      href: conceptual-agent-architecture.md
    - name: Konfigurationen und GitOps
      href: conceptual-configurations.md
    - name: Clustererweiterungen
      href: conceptual-extensions.md
    - name: Clusterverbindung
      href: conceptual-cluster-connect.md
    - name: Benutzerdefinierte Standorte
      href: conceptual-custom-locations.md
    - name: Azure RBAC
      href: conceptual-azure-rbac.md
    - name: Häufig gestellte Fragen
      href: faq.md
    - name: CI/CD-Workflow mit GitOps
      href: conceptual-gitops-ci-cd.md
- name: Anleitungen
  items:
    - name: Verbinden eines Clusters mithilfe eines Dienstprinzipals
      href: create-onboarding-service-principal.md
    - name: Upgrade von Agents
      href: agent-upgrade.md
    - name: Szenarien
      items:
        - name: Bereitstellen von Helm-Charts mithilfe von GitOps
          href: use-gitops-with-helm.md
        - name: Erzwingen von GitOps mithilfe von Azure Policy
          href: use-azure-policy.md
        - name: Bereitstellen und Verwalten von Clustererweiterungen
          href: extensions.md
        - name: Überwachen mithilfe von Azure Monitor für Container
          href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Erzwingen des Bedrohungsschutzes mithilfe von Azure Defender
          href: ../../security-center/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Zugangskontrollrichtlinien mit Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Ortsunabhängiges Herstellen sicherer Verbindungen mit Clustern
          href: cluster-connect.md
        - name: Verwenden von Azure AD RBAC für Autorisierungsüberprüfungen
          href: azure-rbac.md
        - name: Erstellen benutzerdefinierter Standorte
          href: custom-locations.md
        - name: Bereitstellen von IoT-Workloads
          href: deploy-azure-iot-edge-workloads.md
    - name: Problembehandlung
      href: Troubleshooting.md
- name: Referenz
  items:
    - name: Azure Policy-Integrationen
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Ressourcen
  items:
    - name: Einstieg in Azure Arc
      href: 'https://azurearcjumpstart.io'